### ISSUE TITLE
Suggestion: Implement GetTriggerParameter on StateMachine

### ISSUE THREAD

**Issue by pardahlman** [dotnet-state-machine/stateless#113]
Hi again,

In my implementation, I get to a place where I want to fire with a trigger parameter. I have access to the statemachine as well as the payload (arg) I want to fire with. The only way I've found to do this operation is to create a new instance of the trigger parameter like this

```csharp
var paramTrigger = new StateMachine<TState, TTrigger>.TriggerWithParameters<TPayload>((trigger);
return StateMachine.FireAsync(paramTrigger, payload);
```
Due to the fact that the `TriggerWithParameters` is an nested class under the `StateMachine` the code isn't that beautiful. I would like it if there was an convenience method on the state machine that allowed me to change the code above to

```csharp
var paramTrigger = StateMachine.GetTriggerParameter<TPayload>(trigger);
return StateMachine.FireAsync(paramTrigger, payload);
```
It would be even better in the `paramTrigger` was null if there is no such `TriggerWithParameters` registered for that trigger and state machine. ~~That would mitigate parts of the problem i described in #111~~, Update: on second thought, no it would not help for that scenario.

Thought on this? I'll be happy to create a PR if this functionality is desired.

**Comment by nblumhardt** [comment]
Thanks for getting in touch!

The idea of strongly-typed triggers is to link the declaration of the trigger with its firing and with any actions that use the trigger. I think this change would weaken the design a little by removing the 'type safety' aspect - a trigger configured to accept an `int` could be accidentally fired with a `string`, and no compile-time check would detect it.

Is your issue here and in #111 solved by simply duplicating the trigger value? E.g. if your trigger is `Triggers.Close` and you have two variants - one that accepts a `string` reason, and one that does not, could you create a value `Triggers.CloseWithReason` to distinguish between the two?

Cheers!

**Comment by pardahlman** [comment]
Hello - hi! Not 100% sure I follow, so bear with me.

I'm not arguing for a change in the underlying trigger parameters class. The `paramTrigger` would still be of type `StateMachine<TState, TTrigger>.TriggerWithParameters<TPayload>`, it's just that I could implicit declare it if there was an convenience method on the state machine (as it, in turn is a `StateMachine<TState, TTrigger>`). My example above could be written with explicit declaration

```csharp
StateMachine<TState, TTrigger>.TriggerWithParameters<TPayload> paramTrigger = StateMachine.GetTriggerParameter<TPayload>(trigger);
return StateMachine.FireAsync(paramTrigger, payload);
```
If this change is accepted, a nice bonus would be to get an indication if that specific trigger parameters is registered for the instance of the state machine.

> Is your issue here and in #111 solved by simply duplicating the trigger value?

For my scenario, your suggestion would be an acceptable workaround rather than the desired solution. I have a ["saga class"](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/Phone/PhoneCallSaga.cs) that registers the states and triggers of the statemachine, and a seperate ["trigger invokation class"](https://github.com/pardahlman/RawRabbit/blob/2.0/test/RawRabbit.IntegrationTests/StateMachine/Phone/PhoneCallTriggers.cs#L17-L19) that declares external events that triggers/fires the state machine.

```csharp
trigger.Configure(Trigger.CallConnected)
	.FromMessage<PhonePickedUp>(up => up.CallId)
        .FromManualIntervention()
	.FromTimeSpan(TimeSpan.FromSeconds(5));
```
I could add a new trigger for each potential source of the event fire (e.g. `Trigger.CallConnectedFromMessage`, `Trigger.CallConnectedFromManualIntervention` etc, but then my trigger enum would grow significantly and be coupled with the external triggers.

Let me know if you want me to clarify what I mean further, and thanks again!
P

**Comment by pardahlman** [comment]
`StateMachine` in my example is an an instance of a `StateMachine<TState, TTrigger>`. I copied the code from my project where it is an protected field, hence the pascal casing.

**Comment by nblumhardt** [comment]
Thanks for all the detail. By the strong-typing thing, I mean that usually, the trigger object passed to `Fire()` is the one returned by `SetTriggerParameters()`:

```csharp
var assignTrigger = stateMachine.SetTriggerParameters<string>(Trigger.Assign);

stateMachine.Configure(State.Assigned)
    .OnEntryFrom(assignTrigger, email => OnAssigned(email));

stateMachine.Fire(assignTrigger, "joe@example.com");
```

The `assignTrigger` object links the declaration of the trigger's parameters with the `Fire()` call site.

Because of this, if the initial declaration is changed (e.g. the `string` in `SetTriggerParameters<string>()` became `int`), then further on things like the `OnEntryFrom()` action and the `Fire()` call itself won't compile unless they're updated to now use `int`.

In a piece of infrastructure code I can see how this is a bit tricky, because the strongly-typed trigger object needs to be passed around, but I'm not in favour of adding `GetTriggerParameters()` because then, "vanilla" usage of the state machine might drift towards using that pattern rather than following the intended design.

Would declaring all of your triggers to accept `object` (or `object[]`) work better with the wrapper you're building?

Hope this helps, and thanks for the follow-up!
Nick

**Comment by pardahlman** [comment]
Alrightio, I believe I understand what you mean and I appreciate that you curate the project to keep a clean API 👍 .

What you're saying, given that you want to use the same instance of the trigger parameters, is that the primary use case for the state machine is as an internal mechanism with no part exposed outside of the class  (like in the Bug example). Am I right?

I would still argue that it would make sense to allow multiple triggers as proposed in #111. I'm trying to come up with a fitting scenario... so... a bug might have some auto assign event firing after a certain time, or an assigner assigns the bug to an assignee. These scenarios would have different signatures on the bug class 

```csharp
public void Assign(string assigner, string assignee)
public void Assign(TimeSpan autoAssign, string assignee)
public void Assign(string assignee)
```
I see how I could solve this with only one trigger parameter, but it would be convenient if I just could declare three.

Anyways I accept the arguments for not adding the `GetTriggerParameters`, so this ticket can be closed. If you feel strongly that the state machine only going to accept one trigger parameter per trigger, then #111 can be closed as well, I have to make due with the object solution you proposed :)

Last question... would you consider adding a param argument to `CanFire` that answers the questoin "can fire with these trigger parameters"?

**Comment by nblumhardt** [comment]
Thanks for taking the time to work through it. I think these are both reasonable directions Stateless could go in, but at least at this point I'm hesitant to change the model in this way. If you end up blocked, please do reach out though - I still hope we can accommodate your scenario fairly cleanly. Cheers!

**Comment by rustybox** [comment]
I had similar feelings, but found I could avoid the verbose classes by subclassing for a given parameter type e.g. 

```csharp
    public class TriggerWithEvent : StateMachine<OrderState, OrderTrigger>.TriggerWithParameters<IMediator>
    {
        public TriggerWithEvent(OrderTrigger trigger)
             : base(trigger)
        { }
    }
```

This subclass can then be used later e.g.

```csharp
    await _stateMachine.FireAsync(new TriggerWithEvent(OrderTrigger.SetCustomer), mediator);
```

Sadly I can't find a way to initialize the state machine using my subclass so that can be a bit confusing (unless there's a public available way to SaveTriggerConfig? can't say I looked for long)
