### ISSUE TITLE
Suggestion: Import statemachine from json file

### ISSUE THREAD

**Issue by jk1980** [dotnet-state-machine/stateless#115]
Hi,
as a user I would like to have possibility to load statemachine from json file. This will help me store the statemachine workflow in database.

**Comment by HenningNT** [comment]
That something you would have to do yourself, please check out issue #104 for inspiration.

**Comment by nblumhardt** [comment]
In addition - it might not be immediately obvious, but you can use `string` as the type for triggers and/or states, making the whole thing quite dynamic.

The design of Stateless (e.g. lambdas for actions etc.) doesn't accommodate this kind of persistence, but since the state itself can be serialized most apps just re-construct the state machine and then set the underlying state field to whatever comes from the database.

Closing this as we have a few similar threads, as pointed out by @HenningNT. Cheers!
