### ISSUE TITLE
State storing arbitrary state data

### ISSUE THREAD

**Issue by ronnyek** [dotnet-state-machine/stateless#200]
So I've been able to load and save actual state (as in an enum value) and dynamically invoke, and that all works... but I'm looking at the example of phone call example... and it seems like something like existing volume might make sense to store into "state"

My question is... is it possible to have state value on the state objects and have this make any sort of sense? I ask because as soon as I start TRYING to wrap up enum up in an object, the state transitions start getting weird. Or API seems like it just doesnt support it. 

I think there is potential here to get the wrong idea about what sort of "state data" but I do feel like it'd be super convenient to be able to add/set data on the state object and still have the statemachine read/write.

**Comment by HenningNT** [comment]
Technically, all the internal data of an object is "state". I like to divide it into external and internal state. The external state can be exposed, and is a subset of all the possible states that the object can have. Since the phoneCall uses an int for volume it can have 2^32 different internal states, but that's not very useful to take action on each of those... So the volume is supporting data, it's needed to represent the object, but not needed when executing the state machine.

I'm trying to push a new example to GitHub that create state machines from JSON, but Github hangs up on me :-(

**Comment by HenningNT** [comment]
I've added a very simple example project to demonstrate how to create a state machine object from a JSON string. Maybe it gives you an idea of how to proceed?
