### ISSUE TITLE
Add support for default sub state in Hierarchical State Machines

### ISSUE THREAD

**Issue by stuartbrownstanbury** [dotnet-state-machine/stateless#21]
Please add a means to specify the default sub state when defining hierarchical states.

**Comment by oysteinkrog** [comment]
I'm not sure why this is necessary?
Can't you just have the parent state be the "default"?

**Comment by nblumhardt** [comment]
Yes, that's the idea I think - the parent state is itself a valid state. But, alternatively, instead of transitioning into the parent state itself, you can also target your transitions directly to the "default" child state. @stuartbrownstanbury have you hit any limitations around this? Some more scenario info would be good. Cheers!
