### ISSUE TITLE
OnEntry

### ISSUE THREAD

**Issue by BrianLChristensen** [dotnet-state-machine/stateless#230]
I dont seem to see the initial OnEntry of the first state firing.  Is the solution to create a throwaway zero state...

**Comment by trgrote** [comment]
Yeah, dummy initial state that you transition to right after all the states have been configured and/or a dummy start trigger that you Fire after Configuration. 

The issue is that you have to set the initial state before you configure the StateMachine and there's no way to force reenter the state after.

**Comment by HenningNT** [comment]
Perhaps the Activate method could be used as an initial transition, if the method was called on-demand instead of on every transition?
