### ISSUE TITLE
Using Classes (not Enums) for State and Trigger

### ISSUE THREAD

**Issue by ramarivera** [dotnet-state-machine/stateless#234]
First of all, great project. Seems really simple for most of the cases with defined states and triggers.

Im evaluating whether to use Stateless in a project we are working on. 
Since our states (must be defined by our user) and triggers (hierarchy) are not simple enough to be modeled as enum, i was trying to refactor one of the examples to use Classes instead to see how it feels.

Is there any caveat I should be aware of?
I'll most likely report back once i refactored the example, but still.

Thanks!

**Comment by HenningNT** [comment]
I've done something that might be somewhat similar.

I used a base class for events, so that I could use sub-classes for specialized events. I still used enums for the trigger type though. This allowed me to put the payload to parameterized triggers in the same object. I'm not perfectly happy abut how parameterized triggers are handled by stateless, but I made it work.

**Comment by HenningNT** [comment]
In case someone finds this question looking for starters on using objects for states and/or triggers, I've put together a small example here:
https://github.com/HenningNT/ObjectsAsStates/blob/master/ObjectsAsStates/ObjectsAsStates/Program.cs
