### ISSUE TITLE
Concurrent States

### ISSUE THREAD

**Issue by asaywitz** [dotnet-state-machine/stateless#25]
We would like to extend Stateless to support multiple concurrent states. For example, AcceptPayment should transition to both SendConfirmationEmail and OrderFromFactory.  We plan to start out by make TState into List<TState> and go from there. Has anybody tried this yet? Thx! allan

**Comment by HenningNT** [comment]
Don't do that, use another state machine for the Factory-releated states.

**Comment by asaywitz** [comment]
Thanks for the reply. Sorry my example isn't very good. How about after AcceptPayment, you should transition to SendConfirmationEmail and ShowPrintableReceipt. Our client is telling us there are cases where two activities should be done concurrently. And we must be able to track the status of both activities and display the status of each to the user. Seems like the other solutions we found to handle this are so bloated, it would be better to see if we can first try to enhance stateless.

**Comment by HenningNT** [comment]
SendConfirmationEmail sounds like an action, and not a state. Maybe that action can be executed in a transition?

Printing receipts and sending email sounds like two independent actions and/or state, and could be modelled on two separate state machines.

HenningNT

----- Opprinnelig melding -----
Fra: "asaywitz" <notifications@github.com>
Sendt: ‎06.‎07.‎2015 16:24
Til: "nblumhardt/stateless" <stateless@noreply.github.com>
Kopi: "HenningNT" <henning.negaardtorsteinsen@gmail.com>
Emne: Re: [stateless] Concurrent States (#25)

Thanks for the reply. Sorry my example isn't very good. How about after AcceptPayment, you should transition to SendConfirmationEmail and ShowPrintableReceipt. Our client is telling us there are cases where two activities should be done concurrently. And we must be able to track the status of both activities and display the status of each to the user. Seems like the other solutions we found to handle this are so bloated, it would be better to see if we can first try to enhance stateless.

**Comment by asaywitz** [comment]
Thanks again. Its hard to come up with a good example because we are still waiting to get our requirements from the users :) But what we are told by management is we need to track two concurrent manual tasks and we will need synchronization to make sure the concurrent tasks are done before moving ahead in the workflow. Basically simple diamond shape workflow. A triggers B and C but D cannot finish unless B and C are done. That's why I don't think using a separate workflow will work for us.

**Comment by HenningNT** [comment]
Hi, I think this falls into the "hierarchical state machine" pattern.

If not, you could have two triggers that both have a guard condition. 

OnEmailSent will set the MailSent to true, but the guard condition is that ReceptPrinted is true.

OnReceiptPrinted will set ReceiptPrinted to true, but the guard condition is that MailSent is true.

Make sure events (triggers) are evaluated atomically, or this could hang...

H

----- Opprinnelig melding -----
Fra: "asaywitz" <notifications@github.com>
Sendt: ‎06.‎07.‎2015 17:33
Til: "nblumhardt/stateless" <stateless@noreply.github.com>
Kopi: "HenningNT" <henning.negaardtorsteinsen@gmail.com>
Emne: Re: [stateless] Concurrent States (#25)

Thanks again. Its hard to come up with a good example because we are still waiting to get our requirements from the users :) But what we are told by management is we need to track two concurrent manual tasks and we will need synchronization to make sure the concurrent tasks are done before moving ahead in the workflow. Basically simple diamond shape workflow. A triggers B and C but D cannot finish unless B and C are done. That's why I don't think using a separate workflow will work for us.

**Comment by asaywitz** [comment]
Yep thanks. I think we might be able to get the hierarchical to work but its not a clean solution for us. We just need to know that B and C are both running and but they are not related at all. We want to save the hierarchical support for when we really want it like for a cancel or something. I will let you know how it turns out. Someone on my team is already working to enhance stateless to support the multiple states at the same time. We are definitely going to keep the whole state machine single threaded to keep things simple :) thx again H

**Comment by nblumhardt** [comment]
Workflow of this nature is outside the scope of what can be implemented in the statemachine itself. Roughly speaking, you can store a list of outstanding tasks alongside the statemachine, and use conditional transitions to only move forward when both/all outstanding tasks are done. Sorry not to be able to write a complete example - started down that path but there are two many assumptions to make about how you run the concurrent jobs. HTH!

**Comment by asaywitz** [comment]
Thanks Nicholas :)
