### ISSUE TITLE
What's next for Stateless?

### ISSUE THREAD

**Issue by HenningNT** [dotnet-state-machine/stateless#253]
I'd like to push out v4.1 as soon as #249 has been resolved, one of the features added are firing modes.

What should be in v4.2?

**Comment by prlaba** [comment]
1) Add `InitialSubstate(state)` syntax to define a superstate's initial substate.  A transition ending in the superstate (not one of its substates) results in an automatic transition to its defined initial substate.  If no initial substate is defined, the transition ends in the superstate.

2) In the case of hierarchical states, where multiple states in the hierarchy handle the same event with guards, provide a way to determine which state, if any, handled the event. (e.g., `A` is a substate of `B`.  `A` and `B` both handle event `E`.  `A`'s handler includes a guard.  If event `E` is fired from `A`, and `A`'s guard fails, `B` handles the event.)

Paul

**Comment by prlaba** [comment]
Thanks.  My no. 1 suggestion is higher priority, although the workaround currently is to simply add an entry method to each superstate that fires an event to transition to the desired initial substate.

My no. 2 is a suggestion in the context of testing/debugging a state machine.  In a deeply nested hierarchical state machine, it’s not unusual to have the same event handled differently by various substates.  In validating the state machine structure its often useful to know which state in the hierarchy successfully handled a fired event.

This suggestion is really a small piece of a bigger request for Stateless to provide more access to its “inner workings,” but do so out of band from the state machine’s configuration.  One way to do this would be to have Stateless raise .NET events at various points in the state machine's internal operation (firing of an event, exiting a state, entering a state, performing a transition action, failing an event handler’s guard condition, etc.), so that a client, such as a test harness or trace log, could simply add (.NET) event handlers for those events, and use the returned information (in the passed e EventArg object) to validate the state machine’s configuration or display the state machine’s action.

Continuing the example I gave earlier, suppose state `A` is a substate of state `B` and state `C` is a substate of state `D`.  I could imagine subscribing to .NET events that would allow me to produce a trace log like this:

```
Event E fired from state A.
Event E guard failed in state A.
Event E handled in state B.
Transitioning to state C.
Exiting state A.
Exiting state B.
Entering state D.
Entering state C.
Transition to state C complete.
Transition path: A -> B -> D -> C
```

While it’s possible to do most of this by adding trace statements to the event, entry and exit methods of every state in the state machine, and wiring directly into every event firing method, that’s pretty unworkable for all but trivial state machines.

Perhaps this capability already exists in Stateless and I’m simply not aware of how to tap into it.

Thanks,

Paul

**Comment by HenningNT** [comment]
Initial transitions should be fairly easy to add...
How about this:

        var sm = new StateMachine<State, Trigger>(State.A);
            sm.StateEntry += Sm_StateEntry;
            sm.StateExit += Sm_StateExit;

            sm.Configure(State.A).Permit(Trigger.X, State.B);

            sm.Configure(State.B)
                .InitialTransition(State.C);

            sm.Configure(State.C)
                .InitialTransition(State.D)
                .SubstateOf(State.B);

            sm.Configure(State.D)
                .SubstateOf(State.C);

            sm.Fire(Trigger.X);
            Assert.Equal(State.D, sm.State);

I'll get 4.1 out of the door, and add this to v4.2. I have working code for the above, but I want to add more tests for it to be sure it works 100%.

**Comment by prlaba** [comment]
Sounds great!  `.InitialSubstate` would be my preferred syntax as it makes clear it applies to superstates (states with substates).  But `.InitialTransition` works too.

A few points of clarification, just to make sure I understand the implementation:

1. (obvious but worth stating)  A state’s defined initial transition occurs if and only if the _target_ of a transition is that state. The initial transition is not taken if a transition’s target is one of the state’s substates.  So if state `A` has substates `B` and `C`, and `A` has a defined initial transition to `B`, transitions to `A` results in the initial transition to `B`, but transitions to `B` or `C` would ignore `A`’s defined initial transition (to `B`)

2. A transition to a superstate with a defined initial transition invokes the entry methods of the superstate and all states between the superstate and the target substate of the initial transition. In the above example, transitioning to state `A` would invoke the entry methods of both `A` and `B`.

3. Initial transitions are applied recursively.  If `C` is a substate of `B` and `B` is a substate of `A`, with `A` defining initial transition to `B`, and `B` defining initial transition to `C`, then a transition to state `A` will end in state `C`, invoking the entry methods of states `A`, `B` and `C` in the process.

One other question: Is there a way to enforce that the state specified in an `.InitialTransition` clause is a substate of the defining state?  For example, if `B` is _not_ a substate of `A`, what happens if I specify for State A, `.InitialTransition(state.B)`?  

As a consequence of the above, there are some interesting edge cases that can result (in an infinite loop) if a state were to define itself as the target of its initial transition (e.g., `A -> A -> ...`), or define one of its superstates as the target of its initial transition (e.g., `A -> B -> A -> B -> ...`). Any way to detect this in the configuration?

Thanks for doing this!

Paul

**Comment by HenningNT** [comment]
I need to add more tests for this feature, but so far I got 1, 2 and 3 covered.

Currently a initial transition to external state would be executed if the source state has substates :-D  There's no check to see if the configuration is valid when configuring the states.

The first edge case is easy to prevent, but catching the other might restrict the configuration order i.e. substates would have to be configured before superstates. There is already a cyclic configuration check for sub and superstates, that could maybe be recycled as a initial transition loop check.

**Comment by prlaba** [comment]
I think _buyer beware_ is certainly acceptable when using the new syntax. :-)

It would great if there were a way to catch invalid hierarchy configurations, but certainly not a showstopper.  Most major configuration errors will show up pretty quickly at runtime.

Thanks again,

Paul

**Comment by HenningNT** [comment]
V4.2 has been released.
