### ISSUE TITLE
After reenter Main-State from Substate OnExit of Main-State is fired

### ISSUE THREAD

**Issue by Arweenius** [dotnet-state-machine/stateless#260]
#191 
When Trigger X is fired, It will run OnExit and then OnEntry after Changing from substate A to B.
Do you really want OnExit from Mainstate B fired when you leave the substate ?

**Comment by HenningNT** [comment]
If I understand you correctly then yes, when leaving a substate (any state, actually) then the exit action should be executed.
A state diagram or example code makes it easier to understand the context.

**Comment by Arweenius** [comment]
Yes that's right, but in my understanding the exit action from the substate should be executed.
And after that the entry action from the root state.
But in the current version the exit action from the rootstate is executed and then the entry action.

**Comment by prlaba** [comment]
Assuming A is a substate of B, transitioning from A to B must invoke A’s Exit method, then B’s Entry method.  If that’s not what’s happening, then it’s a bug.

Also, if B has an initial substate defined (new feature), then the transition continues to B’s initial substate, calling that state’s Entry method.  And this must be done recursively, in the case of nested substates, each with its own initial substate.

**Comment by HenningNT** [comment]
@Arweenius, I'd like to see the code that is troubling you. While playing around with Reentrant trigger I did find another bug, and I'd like to know if you have found the same. If not at least we can clear any misunderstanding about what we are talking about.

@prlaba That is not quite correct as I have come to understand it. A transition from a sub state to a super state should only execute the exit action of the substate. Since the substate is enclosed by the superstate, the state machine is already in the superstate.

**Comment by Arweenius** [comment]
In this small code example result is:
OnExit B
OnEntry B

but I think "OnExit should not be fired.



class Test
{
    enum Trigger
    {
        X
    }

    enum State
    {
        A,
        B
    }

    public void Foo()
    {
        var sm = new StateMachine<State, Trigger>(State.A);

        sm.Configure(State.B)
            .OnEntry(t => OnEntryB())
            .PermitReentry(Trigger.X)
            .OnExit(t => OnExitB());

        sm.Configure(State.A)
            .SubstateOf(State.B);

        sm.Fire(Trigger.X);
    }

    public void OnEntryB()
    {
        Console.WriteLine("OnEntry B");
    }

    public void OnExitB()
    {
        Console.WriteLine("OnExit B");
    }

}

**Comment by prlaba** [comment]
Hmm...

Are there any other instances in Stateless where a transition to target state T does _not_ invoke T’s entry method? (Or a transition from state S does not invoke S’s exit method?)

It’s certainly true that transitions between substates should not invoke their superstate’s entry or exit methods, since those transitions remain local to the superstate.  But this case is different: the transition is from a substate to its superstate.   (It’s uncommon for a substate to transition to its superstate — normally a substate would transition to another substate within its superstate, or transition out of its superstate.)

I did find this info on the topic (“A crash course in UML state machines: Part 2”, Miro Samek, March 09, 2009):

> Local versus external transitions
> Before UML 2, the only transition semantics in use was the external transition, in which the main source of the transition is always exited and the main target of the transition is always entered. UML 2 preserved the "external transition" semantics for backward compatibility, but also introduced also a new kind of transition called local transition [8, Section 15.3.15].
> 
> For many transition topologies, external and local transitions are actually identical. However, a local transition doesn't cause exit from the main source state if the main target state is a substate of the main source. _In addition, local state transition doesn't cause exit and reentry to the target state if the main target is a superstate of the main source state._ [my emphasis]
> 

This supports Stateless’s implementation, that a transition from a substate to its superstate is local to the superstate, in which case the superstate’s entry and exit methods are not invoked.

I stand corrected.

**Comment by HenningNT** [comment]
@Arweenius Did you get the information you needed?

**Comment by HenningNT** [comment]
I guess this is the sequence you want:
EnterSuper
EnterSub
ExitSub
ExitSuper
EnterSuper

How about this?

            var sm = new StateMachine<string, string>("someState");

            sm.Configure("someState")
                .Permit("GoSuper", "SuperState");

            sm.Configure("SuperState")
                .OnEntry(() => Console.WriteLine("EnterSuper"))
                .PermitReentry("aTrigger")
                .Permit("GoSub", "SubState")
                .OnExit(() => Console.WriteLine("ExitSuper"));

            sm.Configure("SubState")
                .SubstateOf("SuperState")
                .OnEntry(() => Console.WriteLine("EnterSub"))
                .OnExit(() => Console.WriteLine("ExitSub"));

            Console.WriteLine("Fireing 'GoSuper' to transition to superstate.");
            sm.Fire("GoSuper");
            Console.WriteLine("Fireing 'GuSub' to transition into substate.");
            sm.Fire("GoSub");
            Console.WriteLine("Fireing 'aTrigger' to do a self transition from the superstate.");
            sm.Fire("aTrigger");

            Console.ReadKey();

**Comment by Arweenius** [comment]
@HenningNT 
Almost right, but I don't want to ExitSuper
EnterSuper (run special code)
EnterSub
ExitSub 
EnterSuper (run special code)

**Comment by HenningNT** [comment]
I'm afraid it is impossible to not execute the exit action. However I think you might get what you need if you use InternalTransition, or add another substate.

**Comment by technolas** [comment]
@HenningNT

> I'm afraid it is impossible to not execute the exit action.

But Stateless worked this way  before version 4.0.1
And there is no clue about the new behavior in the release notes. What is the actual reason behind this?
Thank you.

**Comment by HenningNT** [comment]
If it ran like that before 4.0.1 then I'm afraid that was a bug.
