### ISSUE TITLE
Change state without trigger

### ISSUE THREAD

**Issue by wvdvegt** [dotnet-state-machine/stateless#277]
For navigation in a Xamarin app I use stateless. Works nice, but i now want to have a different initial state if the app is started in a particular way. 

Is there a way to do this without firing triggers?

Reason: due to a strange Xamarin/Android issue a FireAsync works when used from a button click but fails when the app is started differently and the FireAsync is in the startup code of the app. 

Changing the initial state  is off-course a but of a workaround (if possible at all).

Can InitialTransition do the trick?

**Comment by HenningNT** [comment]
When you instantiate a new state machine you can specify the initial state, so could you figure out how the app was started and select the best initial state?

InitialTransition does not work in the initial state machine instantiation, it is only used when entering a state.

It is also possible to provide stateless with two mewthods to read and write the state. Check the "external state storage" of the [documetation](https://github.com/dotnet-state-machine/stateless#external-state-storage). The docs are a bit light, but if you use methods instead of lambdas you can call the state setter from outside of the state machine, and set (force) the state manually. IIRC, no entry/exit action will be executed when doing this.
