### ISSUE TITLE
[Feature] History, GoBack and MoveToState

### ISSUE THREAD

**Issue by earthlion** [dotnet-state-machine/stateless#355]
Hi there

I have a request for following features:
- History: Keep track of all visited states and its parameters
- Go Back: Visit the previous state
- MoveToState: Move to a state without a trigger

Tell me what you think.

Best regards

**Comment by uygary** [comment]
I have a few of concerns about these suggestions:

- History:

This could potentially be an issue for a long running application like a server. Keeping track of history would mean constantly growing memory consumption and potentially an eventual `OutOfMemoryException`. There could be safeguards put in place to avoid this, like a limit, but apart from being platform and application dependent, that would make the history only partially useful. It could be built as a configurable option, but then the application that uses the state machine already has all the necessary facilities in place to be notified of every state change. Which is why I think this is better suited for the application to handle. I don't think it should be part of the state machine.

- Go Back:

I can certainly see how this can be useful as a quick-and-dirty feature in certain scenarios where the state flow is complex with multiple branches unifying at certain points, but I'm not sure if that should be resolved by the state machine having a step back feature or by a rework of the state flow.
Consider this: As long as a state machine is in a particular state, it shouldn't matter to the machine what the previous state was. If there is any difference that could be introduced by what the previous state was into what the next step should be, that would mean the current state that the two possible previous states transform into should actually be two separate states. Introducing a Go Back feature could potentially lead to bad flow designs. What I'm trying to say here is, if A can transform into B or C, and both B and C can transform into D, whether we should transform from D to B or D to C should be part of the flow logic. If in any case we have the need to revert to B for whatever reason, then I believe the flow shouldn't have been designed as:

```
A -> B1 -> C -> D
        <-

A -> B2 -> C -> D
        <-
```

It should instead be designed as:

```
A -> B1 -> C1 -> D
        <-

A -> B2 -> C2 -> D
        <-
```
Simply because since there is a difference between transforming from C to B1 and transforming between C to B2 without any dependency of another data or action, that means C is not really a state, even if C1 and C2 would essentially have the same functionality other than this possible particular transformation.
Of course it's entirely possible that I'm reading this suggestion and the underlying necessities wrong and not getting the idea at all, so please let me know if that's the case.

- MoveToState:

I sincerely think this is a very bad idea. If there's logic that needs to be triggered by a transition, it should be triggered. State machine shouldn't really decide to ignore any triggers around the flow.
Whether certain actions would be taken or not should really be part of the trigger logic.

**Comment by earthlion** [comment]
Thanks for the detailed response. @uygary 

1) The memory problem can be solved using a FixedSizeQueue, where you define a max size (e.g. 100) and it will automatically feed (Enqueue) in the last and kick out the first on attempted size excess.

2) I think you misunderstood the concept a bit. 
I thought about this scenario: 

![image](https://user-images.githubusercontent.com/60260927/74993677-0a94e800-544c-11ea-9e47-3bbf216fe7c8.png)

Lets say I'd like to go from State 2 to State 1 (both have permits, also vice versa), now I'd like to go back, but I don't know where I came from. Plus there's like 20 of those scenarios in your code, wouldn't it be handy to implement a GoBack feature (or navigational options) in the state machine?

3) I see what you mean, I might have thought a bit short-sighted. But I had imagined that it would save having to interlace back and forward for example in "Go Back" scenarios, especially when you'd like to jump to unknown States w/o permits. Imagine the scenario from 2), path now is State 2 -> State 5 -> State 1 but an additional State 5 is blacklisted in a Go Back Operation and I'd like to go back the same route in between (from State 1 to State 2).

![image](https://user-images.githubusercontent.com/60260927/74994120-79bf0c00-544d-11ea-8761-8cdab9dbec65.png)

Hope it's more clear now :)

**Comment by HenningNT** [comment]
@uygary has some very good reasons why those features (while useful) isn't really what a state machine is supposed to do. However, I won't thell you to go stand in a corner because you've been a naughty boy that wants to violate the holy rules of the FSM.

I'm here to tell you those features are already present in Stateless (but you shouldn't use them).

I think the following example demonstrates two ways to get what you requested, please don't hesitate to ask if anything is unclear. 
The state machine has only two states, and one trigger. No path exists between them, but both states has a dynamic trigger that calls a method to determine the target state. This method access a shared variable, which is set outside of the statemachine.
It also uses the state accessors and state mutator that is supplied at instantiation. These methods can be used for logging, or or serializing. Calling SetState directly sets the current state of the state machine. Notice that stateless does NOT execute the OnEntry/OnExit when this method is used. This is because stateless itself is stateless.

using Stateless;
using System;

namespace ArbitraryStates
{
    enum State { X, Y }
    enum Trigger { A }
    class Program
    {
        private static State currentState;
        private static State targetState;
        static void Main(string[] args)
        {
            var sm = new StateMachine<State, Trigger>(GetState, SetState);

            SetState(State.X);
            GetState();

            sm.Configure(State.X)
                .OnEntry(() => Console.WriteLine("Entering state X"))
                .PermitDynamic(Trigger.A, DestinationSelector)
                .OnExit(() => Console.WriteLine("Exiting state X"));

            sm.Configure(State.Y)
                .OnEntry(() => Console.WriteLine("Entering state Y"))
                .PermitDynamic(Trigger.A, DestinationSelector)
                .OnExit(() => Console.WriteLine("Exiting state Y"));

            Console.WriteLine("Choosing target state Y");
            targetState = State.Y;
            Console.WriteLine("Fire Trigger A");
            sm.Fire(Trigger.A);
            Console.WriteLine("Choosing target state X");
            targetState = State.X;
            Console.WriteLine("Fire Trigger A");
            sm.Fire(Trigger.A);

            SetState(State.Y);
            GetState();

        }

        private static State DestinationSelector()
        {
            return targetState;
        }

        static private void SetState(State newState)
        {
            currentState = newState;
            Console.WriteLine("Setting state to " + currentState);
        }

        static private State GetState()
        {
            Console.WriteLine("Current state is " + currentState);
            return currentState;
        }
    }
}

**Comment by earthlion** [comment]
I see, this seems to be working, thank you for the example.

I have another question: How is it possible to execute an action before permitting?
e.g.
.InternalTransition(Trigger.TurnOn, () => ...)
.Permit(Trigger.TurnOn, State.On)

at the same time?

**Comment by HenningNT** [comment]
Maybe fire another trigger in the InternalTransition, or abuse the PermitIf method; where you execute wanted action and return true.

Or design the state machine in such a way that the action is executed in either Exit- or Entry-action.
