### ISSUE TITLE
Question, how to ignore triggers with certain parameter values?

### ISSUE THREAD

**Issue by boudinov** [dotnet-state-machine/stateless#43]
I have a parametrized trigger, and in most cases, i would like to ignore it, unless it happens with some specific parameter values. How to properly achieve this? The guard expressions in 'If' methods do not receive trigger parameters.
The only way it seems, is to do PermitDynamic, and return the current state if you want to ignore the trigger?
Thanks

**Comment by HenningNT** [comment]
Could you do the evaluation before you Fire a trigger? For instance, in a Control event handler  receiving the KeyPress event; you are only interested in the Enter key being pressed before Processing the input.

Some more information about the specifics of the parameters would be helpful, maybe the state machine could be designed differently?

**Comment by boudinov** [comment]
I have a process workflow, where the triggers are user commands 'Next', 'Back', or a 'DomainEvent', which can be triggered by any type of user or the system itself, and can be anything. 
I cannot evaluate before fire, as different states can be interrested by no events or different types of events.

**Comment by HenningNT** [comment]
Maybe you need to write your own guard logic?
Let's say you have a Next trigger, with the input from the user as payload. The state machine could enter a "ProcessingNextState", where the entry action evaluates the parameters. Based on the required logic you can then fire new Triggers to either advance the process, or to go back to the previous "waiting state".

**Comment by Maximusya** [comment]
"Whitelist" methods family:
- Permit
- PermitIf
- PermitDynamic
- PermitDynamic<>
- PermitDynamicIf
- PermitDynamicIf
- PermitReentry
- PermitReentryIf

"Ignore-list" methods family:
- Ignore
- IgnoreIf

"Blacklist" (to ban Superstate's triggers/transitions) methods
none

Is this disparity intentional or... occasional and is up-for-grabs to implement?

**Comment by nblumhardt** [comment]
Hi @Maximusya  - I think the difference here is intentional. The "dynamic" permit methods select a destination state dynamically, which makes no sense for an ignored trigger. Likewise, "reentry" can't occur if the trigger is ignored.

I think disallowing parent state triggers might indicate a design problem if required in a state machine, since the idea of substates is that they're specialised instances of the superstate. The "blacklisting" concept would be logically similar to removing a method in a subclass in OO design, which is generally a red flag.

Does this match your observations? Cheers!

**Comment by Maximusya** [comment]
> Does this match your observations?

Yes - for Reentry and "blacklisting"
Doubt - for IgnoreDynamic.

I have created a simple gist with 3 versions of similar state machines representing a smart doll that reacts to commands. The goal of the gist is to describe the difference between quiet and loud noises:
- v1 uses plain State and Trigger enums;
- v2 uses parametrised trigger;
- v3 tries to combine both methods - and there are commented .IgnoreDynamic thing. Note how natural it seems to override superstate behavior.

https://gist.github.com/Maximusya/9d921711a46a4c7990125df41ffc136d

**Comment by nblumhardt** [comment]
Great example state machine :-)

```
.IgnoreDynamic(noiseTrigger, vol => vol == NoiseVolume.Quiet); // alternative
```

Isn't this a scenario for `IgnoreIf()`?

Cheers,
Nick

**Comment by Maximusya** [comment]
```csharp
IgnoreIf(TTrigger trigger, Func<bool> guard, string guardDescription = null)
```
It is actually what the opening question was about:
> The guard expressions in 'If' methods do not receive trigger parameters.

While the desirable IgnoreDynamic would have a signature similar to:
```csharp
IgnoreDynamic<TArg0>(TriggerWithParameters<TArg0> trigger, Func<TArg0, bool> guardWithTriggerParameters)
```

I understand that it is rather nice-to-have than should-have feature and I do not lose hope to find time when not at work to submit a proof of concept PR.

**Comment by nblumhardt** [comment]
Thanks for the detailed scenario information. I'm closing this for now but would be interested to develop the idea further if you do end up investigating this again. Cheers!

**Comment by felixcollins** [comment]
A work around for IgnoreDynamic is to just handle it and return the current state. This does trigger re-entry to the state though...
