### ISSUE TITLE
Nuget version different from changelog

### ISSUE THREAD

**Issue by DeepakParamkusam** [dotnet-state-machine/stateless#433]
[Nuget](https://www.nuget.org/packages/Stateless/5.10.0) has the current version as 5.10.0 while CHANGELOG.md has it as 5.2.0. I believe the changelog is correct.

**Comment by HenningNT** [comment]
Doh, it was supposed to be 5.2.0 since I included net5 as a target...

**Comment by HenningNT** [comment]
Fixed now :-D

**Comment by sboptimal** [comment]
@HenningNT I am not sure if it is an issue in that sense but 5.10.0 is still listed on NuGet.org as the latest even though 5.2.0 was pushed more recently due to the version number being higher.  People using the package manager in visual studio will be prompted with version 5.10.0 being the latest even though it isn't an intended version release.  I would guess if you don't delist the 5.10.x it will always be shown as the latest even when you release 5.3.x etc...  until the versions go > 5.10.  I just thought i should mention it.

![image](https://user-images.githubusercontent.com/40687840/108179710-d22af700-70fd-11eb-85e7-c34786a52ba8.png)

**Comment by HenningNT** [comment]
I see... thanks for letting me know!
5.2 and 5.10 are identical, so it's not an immediate issue but it should be sorted.

I can either delist 5.10, or re-release 5.2 as 5.10.1.

I'll re-release 5.2 as 5.10.0. It'll look funny in the changelog, but delisting could be confusing later when we forget about it, and try to release a 5.10...

**Comment by sboptimal** [comment]
I do tend to agree.  Moving to 5.10.0 will sort the issue and prevent future issues.  It is probably the better option than delisting. It just means a jump in your version numbers.  Something probably needing clarification in the change log for reference.

If 5.10.0 and 5.2.0 are identical feature wise other than build times.  I would personally be tempted to leave 5.10.0 as the latest and just push a patch to the change log to indicate as such.  Then make sure new release start after 5.10.0

**Comment by HenningNT** [comment]
I made a new version, so the latest on master is the latest in nuget.
